version: "3.9"

services:
  database:
    image: postgres
    container_name: pg-go-clean-arch
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=go-clean-arch
    volumes:
      - pgdata:/data/postgres


volumes:
  pgdata:
    driver: local